config/routes.rb
# frozen_string_literal: true

Spotlight::Engine.routes.draw do
  devise_for :contact_email, class_name: 'Spotlight::ContactEmail', only: [:confirmations]

  resources :contact_images, controller: :featured_images, only: :create
  resources :exhibit_thumbnails, controller: :featured_images, only: :create
  resources :mastheads, controller: :featured_images, only: :create
  resources :featured_images, only: :create

  resource :site, only: %i[edit update] do
    collection do
      get '/tags', to: 'sites#tags'
    end
  end

  get '/exhibits/edit', to: 'sites#edit_exhibits', as: 'edit_site_exhibits'

  resources :admin_users, only: %i[index create update destroy]

  resources :exhibits, path: '/', except: [:show] do
    member do
      get 'exhibit', to: 'exhibits#show', as: 'get'
      post 'import', to: 'exhibits#process_import'
      patch 'import', to: 'exhibits#process_import'
      post 'reindex', to: 'exhibits#reindex'
    end

    resources :contact_email, only: [:destroy], defaults: { format: :json }
    resources :attachments, only: :create
    resource :contact_form, path: 'contact', only: %i[new create]
    resource :blacklight_configuration, only: [:update]

    resource :appearance, only: %i[edit update]

    resource :metadata_configuration, only: %i[show edit update]
    resource :search_configuration, only: %i[show edit update]
    resource :view_configuration, only: [:show]

    resources :filters, only: %i[create update]
    resources :languages, only: %i[create destroy]

    concern :searchable, Blacklight::Routes::Searchable.new

    resource :catalog, only: [:index], as: 'catalog', path: '/catalog', controller: 'catalog' do
      concerns :searchable

      collection do
        get 'admin'
        get 'autocomplete'
      end
    end

    concern :exportable, Blacklight::Routes::Exportable.new

    resources :solr_documents,
              except: [:index],
              path: '/catalog',
              controller: 'catalog',
              **Spotlight::Engine.config.routes.solr_documents do
      concerns :exportable

      member do
        put 'visibility', action: 'make_public'
        delete 'visibility', action: 'make_private'
        get 'manifest'
      end
    end

    resources :custom_fields
    resources :custom_search_fields

    resource :dashboard, only: [:show] do
      get :analytics
    end

    resources :resources do
      collection do
        get :monitor
        post :reindex_all
      end
    end

    resources :resources_uploads, controller: 'resources/upload', path: 'upload_resources', only: [:create]

    resources :resources_csv_uploads, controller: 'resources/csv_upload', path: 'upload_csv', only: [:create] do
      collection do
        get :template
      end
    end

    resources :iiif_harvesters, controller: 'resources/iiif_harvester', only: :create, as: 'resources_iiif_harvesters'

    resources :searches do
      collection do
        patch :update_all
      end
      member do
        get :autocomplete
      end
    end
    get 'browse/:browse_category_id', to: 'catalog#index', constraints: ->(req) { req.format != :html }
    resources :browse, only: %i[index show]
    get 'browse/group/:group_id', to: 'browse#index', as: 'browse_groups'
    get 'browse/group/:group_id/:id', to: 'browse#show', as: 'browse_group'

    resources :groups, except: %i[show] do
      collection do
        patch :update_all
      end
    end

    resources :tags, only: %i[index destroy] do
      collection do
        patch :update_all
      end

      member do
        post :rename
      end
    end

    resources :contacts, only: %i[edit update destroy]

    resources :pages, only: [:update_all] do
      collection do
        patch :update_all
      end
    end
    resources :about_pages, path: 'about' do
      member do
        get :clone
      end
      collection do
        patch 'contacts' => 'about_pages#update_contacts'
        resources :contacts, only: %i[new create]
        patch :update_all
      end
    end
    resources :feature_pages, path: 'feature' do
      member do
        get :clone
      end
      collection do
        patch :update_all
      end
    end
    resource :home_page, path: 'home', controller: 'home_pages' do
      member do
        get :clone
      end
    end
    resource :bulk_actions, only: [] do
      member do
        post :change_visibility
        post :add_tags
        post :remove_tags
      end
    end

    resource :bulk_updates, only: %i[edit update] do
      collection do
        get :monitor
      end

      member do
        post :download_template
      end
    end

    post '/pages/:id/preview' => 'pages#preview', as: :preview_block
    get '/pages' => 'pages#index', constraints: { format: 'json' }

    resources :lock, only: [:destroy]
    resources :job_trackers, only: [:show]

    resources :roles, path: 'users', only: %i[index create destroy] do
      collection do
        patch :update_all
      end
    end
    post 'solr/update' => 'solr#update'
    resource :translations, only: %i[edit update show] do
      collection do
        post 'import'
        patch 'import'
      end
    end
    get 'iiif/collection' => 'catalog#index', defaults: { q: '*:*', format: :iiif_json }
  end

  get '/:exhibit_id' => 'home_pages#show', as: :exhibit_root
  post 'versions/:id/revert' => 'versions#revert', as: :revert_version
end

app/models/concerns/spotlight/access_controls_enforcement_search_builder.rb
# frozen_string_literal: true

module Spotlight
  # Enforce exhibit visibility for index queries
  module AccessControlsEnforcementSearchBuilder
    extend ActiveSupport::Concern

    included do
      self.default_processor_chain += %i[apply_permissive_visibility_filter apply_exhibit_resources_filter]
    end

    # Adds a filter that excludes resources that have been marked as not-visible
    def apply_permissive_visibility_filter(solr_params)
      return unless current_exhibit
      return if !blacklight_params[:public] && scope&.context&.key?(:current_ability) && scope.context[:current_ability].can?(:curate, current_exhibit)

      solr_params.append_filter_query "-#{blacklight_config.document_model.visibility_field(current_exhibit)}:false"
    end

    def apply_exhibit_resources_filter(solr_params)
      return unless current_exhibit

      current_exhibit.solr_data.each do |facet_field, values|
        Array(values).each do |value|
          solr_params.append_filter_query send(:facet_value_to_fq_string, facet_field, value)
        end
      end
    end

    private

    def current_exhibit
      blacklight_config.current_exhibit
    end
  end
end

app/models/concerns/spotlight/blacklight_configuration_defaults.rb
# frozen_string_literal: true

module Spotlight
  ##
  # Helpers to provide default blacklight configuration values
  module BlacklightConfigurationDefaults
    extend ActiveSupport::Concern

    included do
      before_create :setup_defaults
      attr_accessor :skip_default_configuration
    end

    protected

    def setup_defaults
      return if skip_default_configuration

      default_search_fields
      default_sort_fields
      default_view_types
      set_default_per_page
    end

    def default_search_fields
      return true unless search_fields.empty?

      # can't use default_blacklight_config until after the BlacklightConfiguration
      # is created or we run into a circular dependency.
      default_fields = Spotlight::Engine.blacklight_config.search_fields
      self.search_fields = default_fields.each_with_object({}) do |(k, v), obj|
        obj[k] = { enabled: v.fetch(:enabled, true) }
      end
    end

    def default_sort_fields
      return true unless sort_fields.empty?

      # can't use default_blacklight_config until after the BlacklightConfiguration
      # is created or we run into a circular dependency.
      default_fields = Spotlight::Engine.blacklight_config.sort_fields
      self.sort_fields = default_fields.each_with_object({}) do |(k, v), obj|
        obj[k] = { enabled: v.fetch(:enabled, true) }
      end
    end

    def default_view_types
      return true unless document_index_view_types.empty?

      # can't use default_blacklight_config until after the BlacklightConfiguration
      # is created or we run into a circular dependency.
      self.document_index_view_types = Spotlight::Engine.blacklight_config.view.keys.map(&:to_s)
    end

    def set_default_per_page
      # can't use default_blacklight_config until after the BlacklightConfiguration
      # is created or we run into a circular dependency.
      self.default_per_page ||= Spotlight::Engine.blacklight_config.per_page.first
    end
  end
end

app/models/concerns/spotlight/browse_category_search_builder.rb
# frozen_string_literal: true

module Spotlight
  # Enforce exhibit visibility for index queries
  module BrowseCategorySearchBuilder
    extend ActiveSupport::Concern

    included do
      self.default_processor_chain = %i[apply_browse_category_defaults] +
                                     default_processor_chain +
                                     %i[fix_up_browse_category_defaults fix_up_browse_category_queries]
    end

    # Adds a filter that excludes resources that have been marked as not-visible
    def apply_browse_category_defaults(solr_params)
      return unless current_browse_category

      solr_params.merge!(browse_category_search_builder.to_hash)
    end

    def fix_up_browse_category_defaults(solr_params)
      return if current_browse_category.nil? || search_state.send(:sort_field_key).present?

      solr_params[:sort] = browse_category_search_builder.sort
    end

    def fix_up_browse_category_queries(solr_params)
      return unless solr_params.dig(:json, :query, :bool, :must) && blacklight_params[:q]

      # This replicates existing spotlight 2.x search behavior, more or less. It
      # doesn't take into account the possibility that the browse category query
      # could use a different search field (which.. doesn't have an existing UI
      # control.. and may require additional upstream work to properly encapsulate
      # the two query parameters)
      solr_params[:json][:query][:bool][:must].map! do |q|
        q.is_a?(String) ? { edismax: { query: q } } : q
      end
    end

    private

    def current_exhibit
      blacklight_config.current_exhibit
    end

    def current_browse_category
      return unless current_exhibit && blacklight_params[:browse_category_id].present?

      @current_browse_category ||= current_exhibit.searches.find(blacklight_params[:browse_category_id])
    end

    def browse_category_search_builder
      @browse_category_search_builder ||= begin
        search_builder = self.class.new(@processor_chain, @scope)
        search_builder.with(current_browse_category.query_params)
      end
    end
  end
end

app/models/concerns/spotlight/custom_translation_extension.rb
# frozen_string_literal: true

module Spotlight
  ##
  # Module that extends I18n::Backend::ActiveRecord::Translation to provide
  # additional Spotlight behavior, such as exhibit specific Translations
  module CustomTranslationExtension
    extend ActiveSupport::Concern

    included do
      default_scope { where(exhibit: current_exhibit) }
      belongs_to :exhibit, class_name: 'Spotlight::Exhibit', inverse_of: :translations

      before_validation do
        mark_for_destruction if value.blank?
      end
    end

    class_methods do
      def current_exhibit
        Thread.current[:current_exhibit]
      end

      def current_exhibit=(exhibit)
        I18n.backend.reload! if Thread.current[:current_exhibit] != exhibit

        Thread.current[:current_exhibit] = exhibit
      end
    end
  end
end

app/models/concerns/spotlight/exhibit_analytics.rb
# frozen_string_literal: true

module Spotlight
  ##
  # Exhibit mixin to provide analytics data
  module ExhibitAnalytics
    def analytics(start_date = 1.month, path = nil)
      return OpenStruct.new unless analytics_provider&.enabled?

      @analytics ||= {}
      @analytics[start_date] ||= analytics_provider.exhibit_data(path || self, start_date: start_date.ago)
    end

    def page_analytics(start_date = 1.month, path = nil)
      return [] unless analytics_provider&.enabled?

      @page_analytics ||= {}
      @page_analytics[start_date] ||= analytics_provider.page_data(path || self, start_date: start_date.ago)
    end

    def analytics_provider
      @analytics_provider ||= Spotlight::Engine.config.analytics_provider.new
    end
  end
end

app/models/concerns/spotlight/exhibit_defaults.rb
# frozen_string_literal: true

module Spotlight
  # Mixin for adding default configuration to exhibits
  module ExhibitDefaults
    extend ActiveSupport::Concern

    included do
      before_create :build_home_page
      before_create :add_site_reference
      after_create :initialize_config
      after_create :initialize_browse
      after_create :initialize_main_navigation
      after_create :initialize_filter
    end

    protected

    def initialize_filter
      return unless Spotlight::Engine.config.filter_resources_by_exhibit

      filters.create field: default_filter_field, value: default_filter_value
    end

    def initialize_config
      self.blacklight_configuration ||= Spotlight::BlacklightConfiguration.create!
    end

    def initialize_browse
      return if searches.present?

      searches.create title: 'All exhibit items',
                      long_description: 'All items in this exhibit.'
    end

    def initialize_main_navigation
      default_main_navigations.each_with_index do |nav_type, weight|
        main_navigations.create nav_type: nav_type, weight: weight
      end
    end

    def add_site_reference
      self.site ||= Spotlight::Site.instance
    end

    def default_filter_field
      "#{Spotlight::Engine.config.solr_fields.prefix}spotlight_exhibit_slug_#{slug}#{Spotlight::Engine.config.solr_fields.boolean_suffix}"
    end

    # Return a string to work around any ActiveRecord type-casting
    def default_filter_value
      'true'
    end

    private

    def default_main_navigations
      Spotlight::Engine.config.exhibit_main_navigation.dup
    end
  end
end

app/models/concerns/spotlight/exhibit_documents.rb
# frozen_string_literal: true

module Spotlight
  # Mixin for retrieving solr documents for a specific exhibit
  module ExhibitDocuments
    ##
    # Retrieve all the solr documents associated with this exhibit, appropriately
    # filtered by the exhibit-specific solr field.
    #
    # @return [Enumerable<SolrDocument>]
    def solr_documents(&block)
      return to_enum(:solr_documents) unless block_given?

      start = 0
      search_params = exhibit_search_builder.merge(q: '*:*', fl: '*')

      response = repository.search(search_params.start(start).to_h)

      while response.documents.present?
        response.documents.each(&block)
        start += response.documents.length
        response = repository.search(search_params.start(start).to_h)
      end
    end

    def exhibit_search_builder
      blacklight_config.search_builder_class.new(exhibit_search_builder_context).except(:apply_permissive_visibility_filter)
    end

    private

    def exhibit_search_builder_context
      OpenStruct.new(blacklight_config: blacklight_config.tap { |x| x.current_exhibit = self })
    end

    def repository
      @repository ||= Blacklight.repository_class.new(blacklight_config)
    end
  end
end

app/models/concerns/spotlight/resources/web.rb
# frozen_string_literal: true

require 'nokogiri'

module Spotlight
  module Resources
    ##
    # Generic web resource harvester base module
    module Web
      extend ActiveSupport::Concern

      included do
        before_create do
          harvest!
        end
      end

      def harvest!
        response = Spotlight::Resources::Web.fetch url
        data[:headers] = response.headers
        data[:body] = response.body
      end

      def body
        harvest! if data[:body].blank?

        @body ||= Nokogiri::HTML.parse data[:body]
      end

      def self.fetch(url)
        Faraday.new(url) do |b|
          b.use FaradayMiddleware::FollowRedirects
          b.adapter Faraday.default_adapter
        end.get
      end
    end
  end
end

app/models/concerns/spotlight/search_builder.rb
# frozen_string_literal: true

module Spotlight
  # Enforce exhibit visibility for index queries
  module SearchBuilder
    extend ActiveSupport::Concern

    include Spotlight::AccessControlsEnforcementSearchBuilder
    include Spotlight::BrowseCategorySearchBuilder
  end
end

app/models/concerns/spotlight/solr_document/atomic_updates.rb
# frozen_string_literal: true

module Spotlight
  module SolrDocument
    ##
    # Solr indexing strategy using Solr's Atomic Updates
    module AtomicUpdates
      def reindex(update_params: { commitWithin: 500 })
        return unless write?

        data = hash_for_solr_update(to_solr)

        blacklight_solr.update params: update_params, data: data.to_json, headers: { 'Content-Type' => 'application/json' } unless data.empty?
      end

      def write?
        Spotlight::Engine.config.writable_index
      end

      private

      def hash_for_solr_update(data)
        Array.wrap(data).map { |doc| convert_document_to_atomic_update_hash(doc) }.reject { |x| x.length <= 2 }
      end

      def convert_document_to_atomic_update_hash(doc)
        output = doc.each_with_object({}) do |(k, v), hash|
          hash[k] = if k.to_sym == self.class.unique_key.to_sym
                      v
                    else
                      { set: v }
                    end
        end
        output[Blacklight::Configuration.default_values[:index].timestamp_field] ||= { set: nil }
        output
      end
    end
  end
end

app/views/spotlight/searches/_form.html.erb
<%= bootstrap_form_for [@search.exhibit, @search], layout: :horizontal, label_col: 'col-md-2 col-sm-2', control_col: 'col-md-7 col-sm-7', data: {form_observer: 'true', autocomplete_exhibit_catalog_path: spotlight.autocomplete_exhibit_search_path(@search.exhibit, @search, q: "%QUERY", format: "json")}, html: {id: 'edit-search'} do |f| %>
  <% if @search.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@search.errors.count, "error") %> prohibited this page from being saved:</h2>

      <ul>
      <% @search.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div role="tabpanel">
    <ul class="nav nav-tabs" role="tablist">
      <li role="presentation" class="nav-item">
        <a href="#search-description" aria-controls="search-description" role="tab" data-toggle="tab" class="nav-link active"><%= t(:'.search_description') %></a>
      </li>

      <li role="presentation" class="nav-item">
        <a href="#search-group" aria-controls="search-group" role="tab" data-toggle="tab" class="nav-link"><%= t(:'.search_group') %></a>
      </li>

      <li role="presentation" class="nav-item">
        <a href="#search-masthead" aria-controls="search-masthead" role="tab" data-toggle="tab" class="nav-link"><%= t(:'.search_masthead') %></a>
      </li>

      <li role="presentation" class="nav-item">
        <a href="#search-thumbnail" aria-controls="search-thumbnail" role="tab" data-toggle="tab" class="nav-link"><%= t(:'.search_thumbnail') %></a>
      </li>
    </ul>


    <div class="tab-content">
      <div role="tabpanel" class="tab-pane active" id="search-description">
        <%= f.text_field :title, control_col: "col-sm-5" %>
        <%= f.text_field :subtitle, control_col: "col-sm-5" %>
        <%= f.text_area :long_description, rows: 5 %>
        <%= f.form_group :search_box, label: { text: t(:'.search_box.label'), class: 'pt-0' }, help: t(:'.search_box.help_block') do %>
          <%= f.check_box :search_box, label: t(:'.search_box.checkbox_label') %>
        <% end %>
        <%= f.form_group label: { text: t(:".default_index_view_type"), class: 'pt-0' } do %>
          <% available_document_index_views.each do |key, view| %>
            <%= f.radio_button :default_index_view_type, key, label: view.display_label %>
          <% end %>
        <% end %>
        <% unless @search.query_params.blank? %>
          <div class="form-group row">
            <label class="col-md-2 col-sm-2 col-form-label"><%= t(:".query_params") %></label>
            <div class="col-md-7 col-sm-7">
              <div class="appliedParams card card-body bg-light d-block">
                <%= render_constraints(@search.query_params) %>
              </div>
            </div>
          </div>
        <% end %>
      </div>
      <div role="tabpanel" class="tab-pane" id="search-group">
        <% if @groups.present? %>
          <p class="instructions"><%= t(:'.group.help') %></p>
          <%= f.collection_check_boxes(:group_ids, @groups, :id, :title, hide_label: true) %>
        <% else %>
          <p class="instructions"><%= t(:'.group.help_no_groups') %></p>
        <% end %>
      </div>
      <div role="tabpanel" class="tab-pane" id="search-masthead">
        <%= f.fields_for :masthead, (@search.masthead || @search.build_masthead) do |m| %>
          <p class="instructions"><%= t(:'.masthead.help') %></p>
          <p class="instructions"><%= t(:'.masthead.help_secondary') %></p>
          <%= render '/spotlight/featured_images/form', f: m, initial_crop_selection: Spotlight::Engine.config.masthead_initial_crop_selection, crop_type: :masthead %>
        <% end %>
      </div>
      <div role="tabpanel" class="tab-pane" id="search-thumbnail">
        <%= f.fields_for :thumbnail, (@search.thumbnail || @search.build_thumbnail) do |m| %>
          <p class="instructions"><%= t(:'.thumbnail.help') %></p>
          <%= render '/spotlight/featured_images/form', f: m, initial_crop_selection: Spotlight::Engine.config.featured_image_thumb_size, crop_type: :thumbnail %>
        <% end %>
      </div>

    </div>
  </div>

  <div class="form-actions">
    <div class="primary-actions">
      <%= cancel_link @search,exhibit_searches_path(@exhibit), class: 'btn-sizing' %>
      <%= f.submit nil, class: 'btn btn-primary' %>
    </div>
  </div>
<% end %>

app/views/spotlight/searches/_group.html.erb
<% group = f.object %>
<%= render layout: 'spotlight/shared/dd3_item', locals: { id: group.id.to_s, field: f, dd3_content_classes: "group" , enabled_method: :published, label_method: :title, label: group.title } do |_, section| %>
  <% case section when nil %>
  <div class="d-flex flex-grow-1">
    <div>
      <%= f.check_box :published, inline: true, hide_label: true %>
    </div>

    <div class="flex-grow-1 mx-2 main">
      <h4 class="card-title h6 mb-0" data-in-place-edit-target=".edit-in-place" data-in-place-edit-field-target="[data-edit-field-target='true']">
        <a href="#edit-in-place" class="field-label edit-in-place"><%= group.title %></a>
        <%= f.hidden_field :title, value: group.title , class: 'form-control form-control-sm title-field', data: {:"edit-field-target" => 'true'} %>
      </h4>

      <div class="card-text">
        <div class=""><%= t :'spotlight.searches.group.category_count', count: group.searches.count %> <%= t :'spotlight.searches.group.unpublished_count', count: group.searches.unpublished.count %> &bull; <%= link_to t(:'helpers.action.view'), exhibit_browse_groups_path(current_exhibit, group) %></div>
        <%= f.hidden_field :id %>
        <%= f.hidden_field :weight, data: {property: "weight"} %>
      </div>
    </div>
    <div class="flex m-2">
      <div class="card-text">
        <%= exhibit_delete_link(group) %>
      </div>
    </div>
  <% end %>
<% end %>

app/views/spotlight/searches/_search.html.erb
<% search = f.object %>
<%= render layout: 'spotlight/shared/dd3_item', locals: { id: search.id.to_s, field: f, dd3_content_classes: "search" , enabled_method: :published, label_method: :title, label: search.title } do |_, section| %>
  <% case section when nil %>
  <div class="d-flex flex-grow-1">
    <div>
      <%= f.check_box :published, inline: true, hide_label: true %>
    </div>

    <div class="pic">
      <%= image_tag(search.thumbnail_image_url || 'spotlight/default_browse_thumbnail.jpg', class: 'img-thumbnail') %>
    </div>

    <div class="flex-grow-1 mx-2 main">
      <h4 class="card-title h6 mb-0">
        <%= search.title %>
        <% if search.subtitle.present? %><span class="subtitle"><%= search.subtitle %></span><% end %>
      </h4>

      <div class="card-text">
        <div class="count"><%= t :'spotlight.searches.search.item_count', count: search.count %></div>
        <div class="actions"><%= exhibit_view_link(search) %> &bull; <%= exhibit_edit_link(search) %> &bull; <%= exhibit_delete_link(search) %></div>
        <%= f.hidden_field :id %>
        <%= f.hidden_field :weight, data: {property: "weight"} %>
      </div>
    </div>
  <% when :additional_options  %>
    <div class="flex-grow-1 mx-2 description">
      <div class="card-text">
        <% if search.long_description.present? %>
          <%= truncate(search.long_description, length: 89) %>
        <% else %>
          <span class="missing-description"><%= t(:'spotlight.searches.search.missing_description_html', link: (link_to action_label(search, :edit_long), [spotlight, :edit, search.exhibit, search])) %></span>
        <% end %>
      </div>
    </div>
  <% else %>
  <% end %>
<% end %>

app/views/spotlight/searches/edit.html.erb
<% content_for(:sidebar) do %>
  <%= render 'spotlight/shared/exhibit_sidebar' %>
<% end %>

<%= curation_page_title %>
<%= render 'form' %>

app/views/spotlight/searches/index.html.erb
<% content_for(:sidebar) do %>
  <%= render 'spotlight/shared/exhibit_sidebar' %>
<% end %>

<%= curation_page_title %>

<% if @searches.empty? %>
  <%= t :'.no_saved_searches' %>
  <% unless @exhibit.searchable? %>
    <p class="instructions alert-warning">
      <%= t(:'.not_searchable_html', href: link_to(t(:'spotlight.configuration.sidebar.search_configuration'), spotlight.edit_exhibit_search_configuration_path(@exhibit))) %>
    </p>
  <% end %>
<% else %>
  <div role="tabpanel">
    <ul class="nav nav-tabs" role="tablist">
      <li role="presentation" class="nav-item">
        <a href="#browse-categories" aria-controls="browse-categories" role="tab" data-toggle="tab" class="nav-link active"><%= t(:'.categories_header') %></a>
      </li>

      <li role="presentation" class="nav-item">
        <a href="#browse-groups" aria-controls="browse-groups" role="tab" data-toggle="tab" class="nav-link"><%= t(:'.groups_header') %></a>
      </li>
    </ul>
    <div class="tab-content">
      <div role="tabpanel" class="tab-pane active" id="browse-categories">
        <p class="instructions"><%= t(:'.categories_instructions') %></p>
        <% unless @exhibit.searchable? %>
          <p class="instructions alert-warning">
            <%= t(:'.not_searchable_html', href: link_to(t(:'spotlight.configuration.sidebar.search_configuration'), spotlight.edit_exhibit_search_configuration_path(@exhibit))) %>
          </p>
        <% end %>
        <%= bootstrap_form_for @exhibit, url: update_all_exhibit_searches_path(@exhibit), layout: :horizontal, control_col: 'col-sm-10' do |f| %>

          <div class="panel-group dd search_admin" id="nested-pages" data-behavior="nestable" data-max-depth="1">
            <ol class="dd-list">
              <%= f.fields_for :searches do |p| %>
                <%= render partial: 'search', locals: { f: p} %>
              <% end %>
            </ol>
          </div>

          <div class="float-right">
            <%= submit_tag t(:'helpers.action.update_all'), class: "btn btn-primary" %>
          </div>
        <% end %>
      </div>
      <div role="tabpanel" class="tab-pane" id="browse-groups">
        <div class="instructions"><%= t(:'.groups_instructions_html') %></div>
        <%= bootstrap_form_for @exhibit, url: update_all_exhibit_groups_path(@exhibit), layout: :horizontal, control_col: 'col-sm-10' do |f| %>

          <div class="panel-group dd search_admin" id="nested-pages" data-behavior="nestable" data-max-depth="1">
            <ol class="dd-list">
              <%= f.fields_for :groups do |p| %>
                <%= render partial: 'group', locals: { f: p} %>
              <% end %>
            </ol>
          </div>

          <div class="float-right">
            <%= submit_tag t(:'helpers.action.update_all'), class: "btn btn-primary" %>
          </div>
        <% end %>
        <%= form_for :group, url: spotlight.exhibit_groups_path(current_exhibit), html: {class: "expanded-add-button"} do |f|%>
          <a href='#add-new' class="btn btn-primary" data-turbolinks="false" data-expanded-add-button="true" data-field-target="[data-title-field]">
            <%= t(:'.add_new_group') %> <%= blacklight_icon('chevron_right') %>
            <span data-title-field="true" class="input-field">
              <%= f.text_field(:title) %>
              <%= f.submit t(:'.save'), data: {behavior: "save"} %>
              <%= f.submit t(:'.cancel'), data: {behavior: "cancel"} %>
            </span>
          </a>
        <%- end -%>
      </div>
    </div>
  </div>
<% end %>