config/routes.rb
# frozen_string_literal: true

Spotlight::Engine.routes.draw do
  devise_for :contact_email, class_name: 'Spotlight::ContactEmail', only: [:confirmations]

  resources :contact_images, controller: :featured_images, only: :create
  resources :exhibit_thumbnails, controller: :featured_images, only: :create
  resources :mastheads, controller: :featured_images, only: :create
  resources :featured_images, only: :create

  resource :site, only: %i[edit update] do
    collection do
      get '/tags', to: 'sites#tags'
    end
  end

  get '/exhibits/edit', to: 'sites#edit_exhibits', as: 'edit_site_exhibits'

  resources :admin_users, only: %i[index create update destroy]

  resources :exhibits, path: '/', except: [:show] do
    member do
      get 'exhibit', to: 'exhibits#show', as: 'get'
      post 'import', to: 'exhibits#process_import'
      patch 'import', to: 'exhibits#process_import'
      post 'reindex', to: 'exhibits#reindex'
    end

    resources :contact_email, only: [:destroy], defaults: { format: :json }
    resources :attachments, only: :create
    resource :contact_form, path: 'contact', only: %i[new create]
    resource :blacklight_configuration, only: [:update]

    resource :appearance, only: %i[edit update]

    resource :metadata_configuration, only: %i[show edit update]
    resource :search_configuration, only: %i[show edit update]
    resource :view_configuration, only: [:show]

    resources :filters, only: %i[create update]
    resources :languages, only: %i[create destroy]

    concern :searchable, Blacklight::Routes::Searchable.new

    resource :catalog, only: [:index], as: 'catalog', path: '/catalog', controller: 'catalog' do
      concerns :searchable

      collection do
        get 'admin'
        get 'autocomplete'
      end
    end

    concern :exportable, Blacklight::Routes::Exportable.new

    resources :solr_documents,
              except: [:index],
              path: '/catalog',
              controller: 'catalog',
              **Spotlight::Engine.config.routes.solr_documents do
      concerns :exportable

      member do
        put 'visibility', action: 'make_public'
        delete 'visibility', action: 'make_private'
        get 'manifest'
      end
    end

    resources :custom_fields
    resources :custom_search_fields

    resource :dashboard, only: [:show] do
      get :analytics
    end

    resources :resources do
      collection do
        get :monitor
        post :reindex_all
      end
    end

    resources :resources_uploads, controller: 'resources/upload', path: 'upload_resources', only: [:create]

    resources :resources_csv_uploads, controller: 'resources/csv_upload', path: 'upload_csv', only: [:create] do
      collection do
        get :template
      end
    end

    resources :iiif_harvesters, controller: 'resources/iiif_harvester', only: :create, as: 'resources_iiif_harvesters'

    resources :searches do
      collection do
        patch :update_all
      end
      member do
        get :autocomplete
      end
    end
    get 'browse/:browse_category_id', to: 'catalog#index', constraints: ->(req) { req.format != :html }
    resources :browse, only: %i[index show]
    get 'browse/group/:group_id', to: 'browse#index', as: 'browse_groups'
    get 'browse/group/:group_id/:id', to: 'browse#show', as: 'browse_group'

    resources :groups, except: %i[show] do
      collection do
        patch :update_all
      end
    end

    resources :tags, only: %i[index destroy] do
      collection do
        patch :update_all
      end

      member do
        post :rename
      end
    end

    resources :contacts, only: %i[edit update destroy]

    resources :pages, only: [:update_all] do
      collection do
        patch :update_all
      end
    end
    resources :about_pages, path: 'about' do
      member do
        get :clone
      end
      collection do
        patch 'contacts' => 'about_pages#update_contacts'
        resources :contacts, only: %i[new create]
        patch :update_all
      end
    end
    resources :feature_pages, path: 'feature' do
      member do
        get :clone
      end
      collection do
        patch :update_all
      end
    end
    resource :home_page, path: 'home', controller: 'home_pages' do
      member do
        get :clone
      end
    end
    resource :bulk_actions, only: [] do
      member do
        post :change_visibility
        post :add_tags
        post :remove_tags
      end
    end

    resource :bulk_updates, only: %i[edit update] do
      collection do
        get :monitor
      end

      member do
        post :download_template
      end
    end

    post '/pages/:id/preview' => 'pages#preview', as: :preview_block
    get '/pages' => 'pages#index', constraints: { format: 'json' }

    resources :lock, only: [:destroy]
    resources :job_trackers, only: [:show]

    resources :roles, path: 'users', only: %i[index create destroy] do
      collection do
        patch :update_all
      end
    end
    post 'solr/update' => 'solr#update'
    resource :translations, only: %i[edit update show] do
      collection do
        post 'import'
        patch 'import'
      end
    end
    get 'iiif/collection' => 'catalog#index', defaults: { q: '*:*', format: :iiif_json }
  end

  get '/:exhibit_id' => 'home_pages#show', as: :exhibit_root
  post 'versions/:id/revert' => 'versions#revert', as: :revert_version
end

app/controllers/concerns/spotlight/catalog.rb
# frozen_string_literal: true

module Spotlight
  ##
  # Spotlight catalog mixins
  module Catalog
    extend ActiveSupport::Concern
    include Spotlight::Base
    include Spotlight::SearchHelper

    included do
      before_action :add_facet_visibility_field
    end

    # Adds a facet to display document visibility for the current exhibit
    # if the user is a curator
    # rubocop:disable Metrics/MethodLength
    def add_facet_visibility_field
      return unless current_exhibit && can?(:curate, current_exhibit)

      blacklight_config.add_facet_field 'exhibit_visibility',
                                        label: I18n.t(:'spotlight.catalog.facets.exhibit_visibility.label'),
                                        query: {
                                          public: {
                                            label: I18n.t(:'spotlight.catalog.facets.exhibit_visibility.public'),
                                            fq: "-#{blacklight_config.document_model.visibility_field(current_exhibit)}:false"
                                          },
                                          private: {
                                            label: I18n.t(:'spotlight.catalog.facets.exhibit_visibility.private'),
                                            fq: "#{blacklight_config.document_model.visibility_field(current_exhibit)}:false"
                                          }
                                        }
    end
    # rubocop:enable Metrics/MethodLength

    def render_curator_actions?
      (current_exhibit && can?(:curate, current_exhibit)) &&
        !(params[:controller] == 'spotlight/catalog' && params[:action] == 'admin')
    end
  end
end

app/controllers/spotlight/catalog_controller.rb
# frozen_string_literal: true

module Spotlight
  ##
  # Spotlight's catalog controller. Note that this subclasses
  # the host application's CatalogController to get its configuration,
  # partial overrides, etc
  # rubocop:disable Metrics/ClassLength
  class CatalogController < ::CatalogController
    include Spotlight::Concerns::ApplicationController
    load_and_authorize_resource :exhibit, class: Spotlight::Exhibit, prepend: true
    include Blacklight::Catalog
    include Spotlight::Catalog
    include Spotlight::Concerns::CatalogSearchContext

    before_action :authenticate_user!, only: %i[admin edit make_public make_private]
    before_action :check_authorization, only: %i[admin edit make_public make_private]
    before_action :redirect_to_exhibit_home_without_search_params!, only: :index

    before_action :attach_breadcrumbs
    before_action :add_breadcrumb_with_search_params, only: :index

    before_action only: :show do
      blacklight_config.show.partials.unshift 'tophat'
      blacklight_config.show.partials.unshift 'curation_mode_toggle'
    end

    before_action only: :admin do
      blacklight_config.view.select! { |k, _v| k == :admin_table }
      blacklight_config.view.admin_table(partials: [:index_compact], document_actions: []) unless blacklight_config.view.key? :admin_table
      blacklight_config.track_search_session = false

      unless blacklight_config.sort_fields.key? :timestamp
        blacklight_config.add_sort_field :timestamp, default: true,
                                                     sort: "#{blacklight_config.index.timestamp_field} desc"
      end
    end

    before_action only: :edit do
      blacklight_config.view.edit(partials: blacklight_config.view_config(:show).partials.dup.insert(2, :edit)) unless blacklight_config.view.key? :edit
    end

    def show
      super

      authenticate_user! && authorize!(:curate, current_exhibit) if @document.private? current_exhibit

      add_document_breadcrumbs(@document)
    end

    # "id_ng" and "full_title_ng" should be defined in the Solr core's schema.xml.
    # It's expected that these fields will be set up to have  EdgeNGram filter
    # setup within their index analyzer. This will ensure that this method returns
    # results when a partial match is passed in the "q" parameter.
    def autocomplete
      (_, @document_list) = search_service.search_results do |builder|
        builder.with(builder.blacklight_params.merge(search_field: Spotlight::Engine.config.autocomplete_search_field, public: true, rows: 100))
      end

      respond_to do |format|
        format.json do
          render json: { docs: autocomplete_json_response(@document_list) }
        end
      end
    end

    def admin
      add_breadcrumb t(:'spotlight.curation.sidebar.header'), exhibit_dashboard_path(@exhibit)
      add_breadcrumb t(:'spotlight.curation.sidebar.items'), admin_exhibit_catalog_path(@exhibit)
      (@response, @document_list) = search_service.search_results
      @filters = params[:f] || []

      respond_to do |format|
        format.html
      end
    end

    def update
      @response, @document = search_service.fetch params[:id]
      @document.update(current_exhibit, solr_document_params)
      @document.save

      try_solr_commit!

      redirect_to polymorphic_path([current_exhibit, @document])
    end

    def edit
      @response, @document = search_service.fetch params[:id]
    end

    def make_private
      @response, @document = search_service.fetch params[:id]
      @document.make_private!(current_exhibit)
      @document.save

      respond_to do |format|
        format.html { redirect_back(fallback_location: [spotlight, current_exhibit, @document]) }
        format.json { render json: true }
      end
    end

    def make_public
      @response, @document = search_service.fetch params[:id]
      @document.make_public!(current_exhibit)
      @document.save

      respond_to do |format|
        format.html { redirect_back(fallback_location: [spotlight, current_exhibit, @document]) }
        format.json { render json: true }
      end
    end

    def manifest
      _, document = search_service.fetch params[:id]

      if document.uploaded_resource?
        render json: Spotlight::IiifManifestPresenter.new(document, self).iiif_manifest_json
      else
        head :not_found
      end
    end

    protected

    def attach_breadcrumbs
      if view_context.current_page?({ action: :admin })
        add_breadcrumb t(:'spotlight.exhibits.breadcrumb', title: @exhibit.title), exhibit_root_path(@exhibit)
      else
        # When not on the admin page, get the translated value for the "Home" breadcrumb
        add_breadcrumb t(:'spotlight.curation.nav.home', title: @exhibit.title), exhibit_root_path(@exhibit)
      end
    end

    ##
    # Override Blacklight's #setup_next_and_previous_documents to handle
    # browse categories too
    def setup_next_and_previous_documents
      if current_search_session_from_browse_category?
        setup_next_and_previous_documents_from_browse_category if current_browse_category
      elsif current_search_session_from_page? || current_search_session_from_home_page?
        # TODO: figure out how to construct previous/next documents
      else
        super
      end
    end

    def setup_next_and_previous_documents_from_browse_category
      index = search_session['counter'].to_i - 1
      response, documents = search_service.previous_and_next_documents_for_search index, current_browse_category.query_params.with_indifferent_access

      return unless response

      search_session['total'] = response.total
      @previous_document = documents.first
      @next_document = documents.last
    end

    def _prefixes
      @_prefixes ||= super + ['catalog']
    end

    ##
    # Admin catalog controller should not create a new search
    # session in the blacklight context
    def start_new_search_session?
      super || params[:action] == 'admin'
    end

    def solr_document_params
      params.require(:solr_document).permit(:exhibit_tag_list,
                                            uploaded_resource: [:url],
                                            sidecar: [:public, { data: [editable_solr_document_params] }])
    end

    def editable_solr_document_params
      custom_field_params + uploaded_resource_params
    end

    def uploaded_resource_params
      if @document.uploaded_resource?
        [{ configured_fields: Spotlight::Resources::Upload.fields(current_exhibit).map(&:field_name) }]
      else
        []
      end
    end

    def custom_field_params
      current_exhibit.custom_fields.as_strong_params
    end

    def check_authorization
      authorize! :curate, @exhibit
    end

    def redirect_to_exhibit_home_without_search_params!
      redirect_to spotlight.exhibit_root_path(@exhibit) unless has_search_parameters?
    end

    def has_search_parameters? # rubocop:disable Naming/PredicateName
      super || params[:browse_category_id].present?
    end

    def add_breadcrumb_with_search_params
      return unless has_search_parameters?

      add_breadcrumb t(:'spotlight.catalog.breadcrumb.index'), spotlight.search_exhibit_catalog_path(params.to_unsafe_h), current: action_name == 'index'
    end

    # rubocop:disable Metrics/AbcSize
    def add_document_breadcrumbs(document)
      if current_browse_category
        add_breadcrumb current_browse_category.exhibit.main_navigations.browse.label_or_default, exhibit_browse_index_path(current_browse_category.exhibit)
        add_breadcrumb current_browse_category.title, exhibit_browse_path(current_browse_category.exhibit, current_browse_category)
      elsif current_page_context&.title&.present? && !current_page_context.is_a?(Spotlight::HomePage)
        add_breadcrumb current_page_context.title, [current_page_context.exhibit, current_page_context]
      elsif current_search_session && !current_page_context&.is_a?(Spotlight::HomePage)
        add_breadcrumb t(:'spotlight.catalog.breadcrumb.index'), search_action_url(current_search_session.query_params)
      end

      add_breadcrumb view_context.document_presenter(document).heading, polymorphic_path([current_exhibit, document])
    end
    # rubocop:enable Metrics/AbcSize

    def additional_export_formats(document, format)
      super

      format.solr_json do
        authorize! :update_solr, @exhibit
        render json: document.to_solr.merge(@exhibit.solr_data)
      end
    end

    def try_solr_commit!
      repository.connection.commit
    rescue StandardError => e
      Rails.logger.info "Failed to commit document updates: #{e}"
    end
  end
end

app/views/catalog/_add_tags.html.erb
<div class="modal fade" id="add-tags-modal" tabindex="-1" role="dialog" aria-labelledby="add-tag-modal" aria-hidden="true">
  <div class="modal-dialog">
  <%= bootstrap_form_for([:visibility, current_exhibit], url: add_tags_exhibit_bulk_actions_path(current_exhibit), method: 'post') do |f| %>
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title" id="add-tag-modal"><%= t(:'spotlight.bulk_actions.add_tags.heading') %></h4>
        <button type="button" class="blacklight-modal-close close" data-dismiss="modal" aria-label="<%= t('blacklight.modal.close') %>">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p>
          <%= t(:'spotlight.bulk_actions.add_tags.description', count: @response.total) %>
        </p>
        <div class="form-group">
          <%= label_tag :tags, t(:'spotlight.bulk_actions.add_tags.label') %>
          <%= text_field_tag :tags, '', class: 'form-control', data: { autocomplete_tag: true, autocomplete_url: exhibit_tags_path(current_exhibit, format: 'json')} %>
        </div>
        <%= render Blacklight::HiddenSearchStateComponent.new(params: search_state.params_for_search) %>
      </div>
      <div class="modal-footer d-flex flex-row-reverse justify-content-start">
        <%= f.submit t(:'spotlight.bulk_actions.add'), class: 'btn btn-primary', data: { confirm: t(:'spotlight.bulk_actions.confirm') } %>
        <button type="button" class="btn btn-link" data-dismiss="modal"><%= t :cancel %></button>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/catalog/_bulk_actions.html.erb
<div class="dropdown bulk-actions-dropdown">
  <button class="btn btn-secondary dropdown-toggle" type="button" id="bulk-actions-button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    <%= t(:'spotlight.bulk_actions.label') %>
  </button>
  <div class="dropdown-menu" aria-labelledby="bulk-actions-button">
    <% blacklight_config.bulk_actions.each do |key, _config| %>
      <%= link_to t("spotlight.bulk_actions.#{key}.heading"), '#', class: 'dropdown-item', data: {toggle:"modal", target:"##{key.to_s.dasherize}-modal"} %>
    <% end %>
  </div>
</div>

<%= render_filtered_partials(blacklight_config.bulk_actions) %>

app/views/catalog/_change_visibility.html.erb
<div class="modal fade" id="change-visibility-modal" tabindex="-1" role="dialog" aria-labelledby="save-modal-label" aria-hidden="true">
  <div class="modal-dialog">
  <%= bootstrap_form_for([:change_visibility, current_exhibit], url: change_visibility_exhibit_bulk_actions_path(current_exhibit), method: 'post') do |f| %>
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title" id="save-modal-label"><%= t(:'spotlight.bulk_actions.change_visibility.heading') %></h4>
        <button type="button" class="blacklight-modal-close close" data-dismiss="modal" aria-label="<%= t('blacklight.modal.close') %>">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p>
          <%= t(:'spotlight.bulk_actions.change_visibility.description', count: @response.total) %>
        </p>
        <div class="form-check-label">
          <%= t(:'spotlight.bulk_actions.change_visibility.label') %>
        </div>
        <% ['public', 'private'].each do |key| %>
          <div class="form-check">
            <%= label_tag "visibility_#{key}", class: 'form-check-label'  do %>
              <%= radio_button_tag :visibility, key, {}, class: 'form-check-input' %>
              <%= t(:"spotlight.bulk_actions.change_visibility.#{key}") %>
            <% end %>
          </div>
        <% end %>
        <%= render Blacklight::HiddenSearchStateComponent.new(params: search_state.params_for_search) %>
      </div>
      <div class="modal-footer d-flex flex-row-reverse justify-content-start">
        <%= f.submit t(:'spotlight.bulk_actions.change'), class: 'btn btn-primary', data: { confirm: t(:'spotlight.bulk_actions.confirm') } %>
        <button type="button" class="btn btn-link" data-dismiss="modal"><%= t :cancel %></button>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/catalog/_curator_actions.html.erb
<div class="curator-actions">
  <%= render_filtered_partials(blacklight_config.curator_actions) %>
</div>

app/views/catalog/_image_default.html.erb
<%# looks suspiciously similar to blacklight's _thumbnail, but skips all the search context + linking -%>
<%- if has_thumbnail?(document) && tn = render_thumbnail_tag(document, { alt: '' }, :suppress_link => true) %>
<div class="img-thumbnail">
  <%= tn %>
</div>
<%- end %>

app/views/catalog/_remove_tags.html.erb
<div class="modal fade" id="remove-tags-modal" tabindex="-1" role="dialog" aria-labelledby="remove-tag-modal" aria-hidden="true">
  <div class="modal-dialog">
  <%= bootstrap_form_for([:visibility, current_exhibit], url: remove_tags_exhibit_bulk_actions_path(current_exhibit), method: 'post') do |f| %>
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title" id="remove-tag-modal"><%= t(:'spotlight.bulk_actions.remove_tags.heading') %></h4>
        <button type="button" class="blacklight-modal-close close" data-dismiss="modal" aria-label="<%= t('blacklight.modal.close') %>">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= t(:'spotlight.bulk_actions.remove_tags.description_html', count: @response.total) %>
        <% facet = @response.aggregations[blacklight_config.facet_fields['exhibit_tags'].field] %>

        <% if facet.items.any? %>
          <h5><%= t(:'spotlight.bulk_actions.remove_tags.assigned') %></h5>
        <% end %>
        <% facet.items.each do |facet_item| %>
          <div class="badge badge-info">
            <%= "#{facet_item.value} (#{facet_item.hits})" %>
          </div>
        <% end %>

        <div class="form-group mt-4">
          <%= label_tag :tags, t(:'spotlight.bulk_actions.remove_tags.label') %>
          <%= text_field_tag :tags, '', class: 'form-control', data: { autocomplete_tag: true, autocomplete_url: exhibit_tags_path(current_exhibit, format: 'json')} %>
        </div>
        <%= render Blacklight::HiddenSearchStateComponent.new(params: search_state.params_for_search) %>
      </div>
      <div class="modal-footer d-flex flex-row-reverse justify-content-start">
        <%= f.submit t(:'spotlight.bulk_actions.remove'), class: 'btn btn-primary', data: { confirm: t(:'spotlight.bulk_actions.confirm') } %>
        <button type="button" class="btn btn-link" data-dismiss="modal"><%= t :cancel %></button>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/catalog/_save_search.html.erb
<%= button_tag t(:'spotlight.saved_search.label'), id: "save-this-search", class: 'btn btn-secondary',  data: {toggle:"modal", target:"#save-modal"} %>
<div class="modal fade" id="save-modal" tabindex="-1" role="dialog" aria-labelledby="save-modal-label" aria-hidden="true">
  <div class="modal-dialog">
  <%= bootstrap_form_for [spotlight, current_exhibit, Spotlight::Search.new] do |f| %>
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title" id="save-modal-label"><%= t(:'spotlight.saved_search.label') %></h4>
        <button type="button" class="blacklight-modal-close close" data-dismiss="modal" aria-label="<%= t('blacklight.modal.close') %>">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= f.text_field :title, label: t(:'spotlight.saved_search.title') %>
        <%= label_tag :id, t(:'spotlight.saved_search.id'), class: 'col-form-label' %>
        <%= select_tag :id, options_for_select(current_exhibit.searches.map { |s| [s.full_title, s.id] }), include_blank: true, class: 'form-control' %>
        <%= render Blacklight::HiddenSearchStateComponent.new(params: search_state.params_for_search.except(:qt, :page)) %>
      </div>
      <div class="modal-footer d-flex flex-row-reverse justify-content-start">
        <%= f.submit nil, class: 'btn btn-primary' %>
        <button type="button" class="btn btn-link" data-dismiss="modal"><%= t :cancel %></button>
      </div>
    </div>
    <% end %>
  </div>
</div>